version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  web:
    build:
      context: .
      dockerfile: apps/web-app/Dockerfile
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: production